### ISSUE TITLE
portmonitor carrier does not work on my YARP installation

### ISSUE THREAD

**Issue by Ommac** [robotology/yarp#426] opened 2015-03-02 10:05 UTC
Hi,

I need to use portmonitor in a YARP application of mine, which has to run on the robot. It used to work some months ago, but now something is not working with my installation of YARP.

In fact, any connection using the portmonitor carrier produces the following message on the receiver side:

```
Carrier "portmonitor" does not modify incoming data as expected.
yarp: Removing input from /write to /read
```

-  I am using YARP on Ubuntu 14.04
-  I have followed the steps provided in http://wiki.icub.org/yarpdoc/portmonitor.html#need
-  I have recompiled and built the latest version of YARP.
-  I have used this example as a test: http://wiki.icub.org/yarpdoc/simple_modification.html and it still provides the same message, so the issue does not seem to depend on my application
-  I have tried to set the LUA_CPATH env var in the ~/.profile (then I issued the "source .profile" command) in the following ways, with no success:
  -  export LUA_CPATH=";;;$YARP_ROOT/bindings/build/?.so"
  -  export LUA_CPATH=";;;$YARP_ROOT/bindings/build/yarp.so"
  -  export LUA_CPATH=";;;$YARP_ROOT/bindings/build/lib/lua/?.so"

Does anybody see the problem here?
May I provide additional information?

Thank you,
Raffaello

**Comment by traversaro** [comment] 2015-04-01 11:17
I can confirm I have the same problem on Ubuntu 14.04 , using the example https://github.com/robotology/yarp/tree/master/example/portmonitor/coder_decoder . As an additional info, in my system yarp-lua bindings are correctly working , because I am testing several lua-based coordination components without problems.

**Comment by drdanz** [comment] 2015-04-01 13:43
@apaikan any idea?

**Comment by apaikan** [comment] 2015-04-01 15:03
A quick test has shown that the `modifiesIncomingData` method of `ModifyingCarrier` class from which the portmonitor modifier class is inherited is not called! 

There has not been any modification to the `portmonitor` carrier for months. So we need to see which commit have broken the carrier... 

I am guessing the problem probably should happen with any carrier modifiers in YARP.

**Comment by Ommac** [comment] 2015-04-01 15:26
Note: I haven't found any solution to this issue in the meantime.

**Comment by apaikan** [comment] 2015-04-01 15:52
finally! 

The commit 7b8a25f48b534f18fa500d61b0d9d29d610284bc has broken the `portmonitor` plugin: 
This has been removed from the `srx/carriers/CMakeLists.txt` : 
`set_property(GLOBAL APPEND PROPERTY YARP_LIBS yarpcar ${yarpcar_LIBRARIES})`

**Comment by drdanz** [comment] 2015-04-01 17:51
Should be fixed now, @Ommac, @apaikan can you confirm please?

**Closed** 2015-04-01 17:50 UTC

**Comment by traversaro** [comment] 2015-04-02 12:08
I can confirm that is now working.

**Comment by apaikan** [comment] 2015-04-02 12:14
me too. good! 

lets close the issue!
