### ISSUE TITLE
Unable to open devices that are dynamically compiled in windows

### ISSUE THREAD

**Issue by mebbaid** [robotology/yarp#1866] opened 2018-09-19 08:00 UTC
**Describe the bug**
When doing `yarpdev --list` the following is displayed

![yarp_error](https://user-images.githubusercontent.com/36491318/45739151-7d17ed80-bbf2-11e8-9b57-80319c63009f.JPG)

When verbose with `yarp plugin --search-path,` the following message appears
![yarp issue](https://user-images.githubusercontent.com/36491318/45739196-9faa0680-bbf2-11e8-8c47-294c8a438475.JPG)

```
$ yarp plugin --search-path
```
gives the following output
```
Search path:
obotology-superbuildbuildinstalllibICUBcontribdegit
obotology-superbuildbuildinstalllibiCubmentscodegit
              hde:      C:/Users/icub/Documents/code/git/human-dynamics-estimation/build/lib/yarp
obotology-superbuildbuildinstalllibyarpmentscodegit
```

**To Reproduce**
Update the robotology superbuild, and then update and build yarp

**Configuration (please complete the following information):**
 - OS: Windows 10
 - yarp version: latest master
-  compiler: VS

@traversaro

**Comment by traversaro** [comment] 2018-09-19 08:12
I think the output of `yarp plugin --search-path` is the most interesting thing. 

On my Linux machine the output is:
~~~bash
straversaro@iiticublap103:~$ yarp plugin --search-path
Search path:
             yarp:	/home/straversaro/src/robotology-superbuild/build/install/lib/yarp
             iCub:	/home/straversaro/src/robotology-superbuild/build/install/lib/iCub
      ICUBcontrib:	/home/straversaro/src/robotology-superbuild/build/install/lib/ICUBcontrib
           codyco:	/home/straversaro/src/robotology-superbuild/build/install/lib/codyco
~~~

I think this could be related to https://github.com/robotology/yarp/pull/1841 or https://github.com/robotology/yarp/issues/1513 . Can you try to see if the issue is present also in the commit 4d82b1e70238d00d45b5504d2e393c36089564dd (the one before  https://github.com/robotology/yarp/pull/1841)?

**Comment by traversaro** [comment] 2018-09-19 08:13
It would be  interesting also to understand why the `hde` search path is working fine. 
Can you paste the content of the `PATH` and `YARP_DATA_DIRS` env variables?

**Comment by traversaro** [comment] 2018-09-19 09:09
What is that %_DIR%` in the `PATH` ?

**Comment by mebbaid** [comment] 2018-09-19 09:14
Type while opening the variable, deleted it but nothing changed.

**Comment by traversaro** [comment] 2018-09-19 12:53
It seems that there was another change in the setup: you installed https://github.com/robotology-playground/wearables I guess on branch `feature/cleanup` and that repo installed the plugins in the same location of YARP, and I guess this is the reason why everything is working.

**Comment by traversaro** [comment] 2018-09-19 13:37
Just for reference, could you print the content of the following files: 
*  robotology-superbuild/build/install/share/yarp/plugins/yarp.ini 
*  robotology-superbuild/build/install/share/iCub/plugins/iCub.ini 
* robotology-superbuild/build/install/share/ICUBcontrib/plugins/ICUBcontrib.ini 
* robotology-superbuild/build/install/share/yarp/plugins/wearables.ini 

On my Linux machine they are: 
~~~
straversaro@iiticublap103:~/src$ cat
###### This file is automatically generated by CMake.
[search yarp]
path "/home/straversaro/src/robotology-superbuild/build/install/lib/yarp"
extension ".so"
type "shared"
straversaro@iiticublap103:~/src$ cat robotology-superbuild/build/install/share/iCub/plugins/iCub.ini 
###### This file is automatically generated by CMake.
[search iCub]
path "/home/straversaro/src/robotology-superbuild/build/install/lib/iCub"
extension ".so"
type "shared"
straversaro@iiticublap103:~/src$ cat robotology-superbuild/build/install/share/ICUBcontrib/plugins/ICUBcontrib.ini 
###### This file is automatically generated by CMake.
[search ICUBcontrib]
path "/home/straversaro/src/robotology-superbuild/build/install/lib/ICUBcontrib"
extension ".so"
type "shared"
~~~

**Comment by mebbaid** [comment] 2018-09-19 13:43
First file: yarp.ini
```
###### This file is automatically generated by CMake.
[search yarp]
path "C:\Users\icub\Documents\code\git\robotology-superbuild\build\install\lib\yarp"
extension ".dll"
type "shared"
```
Second file: iCub.ini
```
###### This file is automatically generated by CMake.
[search iCub]
path "C:\Users\icub\Documents\code\git\robotology-superbuild\build\install\lib\iCub"
extension ".dll"
type "shared"
```
Third File: ICUBcontrib.ini
```
###### This file is automatically generated by CMake.
[search ICUBcontrib]
path "C:\Users\icub\Documents\code\git\robotology-superbuild\build\install\lib\ICUBcontrib"
extension ".dll"
type "shared"
```
wearables.ini
```
###### This file is automatically generated by CMake.
[search wearable]
path "C:\Users\icub\Documents\code\git\robotology-superbuild\build\install\lib\yarp"
extension ".dll"
type "shared"
```

**Comment by mebbaid** [comment] 2018-09-19 13:47
Maybe this is why it finds all the plugins except those of icub, since the correct folder is like in the picture:
![libpath](https://user-images.githubusercontent.com/36491318/45757295-4908f080-bc23-11e8-9628-bac6f39b4eab.JPG)

https://github.com/robotology/yarp/issues/1866#issuecomment-422745458

**Comment by traversaro** [comment] 2018-09-19 13:56
Cool, nice catch.

**Comment by traversaro** [comment] 2018-09-19 13:58
I checked on my system, and there should be both `ICUB` (for CMake config files) and `iCub` (for YARP plugin). Are you sure that the iCub project is actually installing those plugins?

**Comment by mebbaid** [comment] 2018-09-19 14:04
yes, however both the cmakeconfig and the plugins are in the same `ICUB` as in:
![icublib](https://user-images.githubusercontent.com/36491318/45758322-9f772e80-bc25-11e8-90c2-90bdb61c9e48.JPG)

**Comment by mebbaid** [comment] 2018-09-19 14:18
Indeed editing the plugin .ini files path variables manually fixes the corresponding search path returned by `yarp plugin --search-path`
![fix](https://user-images.githubusercontent.com/36491318/45759200-b28afe00-bc27-11e8-9b79-0a1cb00e6739.JPG)

**Comment by mebbaid** [comment] 2018-09-19 14:58
`yarp.ini` after modifying manually:
```
###### This file is automatically generated by CMake.
[search yarp]
path "C:/Users/icub/Documents/code/git/robotology-superbuild/build/install/lib/yarp"
extension ".dll"
type "shared"
```

**Comment by Yeshasvitvs** [comment] 2018-10-12 15:09
@traversaro I ran into this issue today while trying to access the ftShoes. It seems like this problem is fixed in https://github.com/robotology/yarp/pull/1841 but the changes are not reflected yet. Any suggestions on how to proceed to fix it?

**Comment by traversaro** [comment] 2018-10-12 15:14
Hi @Yeshasvitvs , can you provide the output of your `yarpdev --list` and the content of the following files (before/after) your local fixes:

* robotology-superbuild/build/install/share/yarp/plugins/yarp.ini
* robotology-superbuild/build/install/share/iCub/plugins/iCub.ini
* robotology-superbuild/build/install/share/ICUBcontrib/plugins/ICUBcontrib.ini
*  robotology-superbuild/build/install/share/yarp/plugins/wearables.ini

**Comment by Yeshasvitvs** [comment] 2018-10-12 16:14
@traversaro I am using the following YARP master branch with `HEAD` at 

```
commit d1a2effb61bd8888e7b19701d2b6bd24e4f30dd4 (HEAD -> master, origin/master, origin/HEAD)
Merge: 1c95e98c8 4624e7c1e
Author: Daniele E. Domenichelli <daniele.domenichelli@gmail.com>
Date:   Thu Oct 11 11:08:21 2018 +0200

    Merge pull request #1891 from drdanz/fix_VAS_status

    Fix -Wattributes warning for yarp::dev::VAS_status
```

### Before local fixes

![screenshot 4](https://user-images.githubusercontent.com/6505998/46880998-8b9ca200-ce4a-11e8-9477-b4f51424c03f.png)

### After local fixes

![screenshot 7](https://user-images.githubusercontent.com/6505998/46881011-92c3b000-ce4a-11e8-8ea9-24724a8ddf20.png)


**NOTE:** I am not using `wearables` yet

**Comment by traversaro** [comment] 2018-10-12 18:03
Ok, that seems to be super clear. I am surprised because I would expect @claudiofantacci , @pattacini or other regular Windows users to be affected as well.

**Comment by traversaro** [comment] 2018-11-02 14:12
We experienced the same issue with @AngeloRendiniello with latest YARP master branch.

**Comment by traversaro** [comment] 2018-11-02 14:43
I think I understood what is going on: @pattacini and (I guess) @claudiofantacci use devices from the `build` tree, not the `install` tree, and indeed if you check in: 
https://github.com/robotology/yarp/pull/1841/files#diff-cd0eb3dc7250fb8863489a632361de81R92 
the directory separator are not changed in the `_path` of the `yarp.ini` installed in the build `tree`, but it is just modified for the installed one. Fix provided in https://github.com/robotology/yarp/pull/1911 .

**Closed** 2018-11-05 06:48 UTC
Labels: Affects: YARP v3.1.0, Component: Devices, Issue Type: Bug, Platform: Windows
