### ISSUE TITLE
opencv grabber

### ISSUE THREAD

**Issue by mike-talmage** [robotology/yarp#1720] opened 2018-06-01 13:43 UTC
opencv_grabber compiles fine but when i try to use it it says

yarpdev: symbol lookup error: /usr/local/lib/yarp/yarp_opencv.so: undefined symbol: _ZN2cv12VideoCaptureC1Ev

tried it several times every time it does this

**Comment by traversaro** [comment] 2018-06-01 13:52
On which OS are you experiencing this? If Debian/Ubuntu, which version?

**Comment by mike-talmage** [comment] 2018-06-01 14:49
ubuntu 16.04

**Comment by Nicogene** [comment] 2018-06-01 14:50
Did you forget to do `make install` after compiling?

**Comment by mike-talmage** [comment] 2018-06-01 14:51
no every thing works did make install and it went perfect

**Comment by mike-talmage** [comment] 2018-06-01 14:52
no errors or warnings

**Comment by mike-talmage** [comment] 2018-06-01 14:58
using yarp 2.3.70

**Comment by mike-talmage** [comment] 2018-06-01 15:02
if I have to go up its going to be hard my iot only compiles this version

what can I do

**Comment by PeterBowman** [comment] 2018-06-13 12:53
What is the output of `ldd /usr/local/lib/yarp/yarp_opencv.so | grep opencv`?

**Comment by drdanz** [comment] 2018-06-14 19:49
This is something related to your configuration, YARP does not compile if one of the symbols is missing.
Please try again with a clean build...

**Comment by Nicogene** [comment] 2018-06-20 13:16
@mike-talmage any news?
The problem is solved? Shall we close it?

**Comment by Nicogene** [comment] 2018-07-11 10:07
Closing for now, @mike-talmage  feel free to reopen it.

**Closed by Nicogene** 2018-07-11 10:07 UTC
Labels: Issue Type: QA/Support
