### ISSUE TITLE
Manager does not disconnect UDP

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#326] opened 2014-12-02 17:39 UTC
When an application has *UDP* connections and it is stopped without disconnecting the connection first, the other side will not receive a message about the disconnection and will eventually keep sending data to the other side, since UDP does not require an ACK.
This does not happen if you run the command from the command line and then kill it.

**Comment by apaikan** [comment] 2015-01-16 10:12
The manager (on localhost) and the yarprun do exactly what being expected: sending SIGTERM for stopping the modules and SIGKILL for (forced) terminating the processes. 

The problem in not in the manager/yarprun but it seems to be a problem with the `yarpview` itself. even closing the `yarpview` from command line using `killall yarpview` will cause the same problem reported by @drdanz. 

The problem is not replicable with other modules. for example if you replace `yarpview` with `yarp read`  which receives data from a `yarpdev --device test` using udp,  after stopping the `yarp read` using the manager, the sender (`yarpdev --device test`) is notified correctly. 

So i close the issue here. We can and open another one specifically for yarpview.

**Closed by apaikan** 2015-01-16 10:12 UTC
Labels: Component: yarpmanager-console, Component: yarpmanager-gtk, Component: yarpmanager-qt, Component: YARP_manager, Severity: Major, Type: Bug

**Comment by lornat75** [comment] 2015-01-16 10:15
are we talking about the gtk or qt yarpview? maybe the qt implementation does not handle signals.

**Comment by apaikan** [comment] 2015-01-16 10:44
same for both (GTK/QT).  Check #356!
