### ISSUE TITLE
timestamp/envelope problems in portmonitor (only in recv mode) ?

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#782] opened 2016-05-31 12:01 UTC
I'm connecting two ports using a portmonitor plugin.
In **send** mode the timestamp/envelope is ok.
In **recv** mode the timestamp/envelope seems to be missing (e.g. in following snippet of code, taken from **camCalibWithPose** time is always=0). 

```c++
void HeadEncoderPort::onRead(yarp::os::Bottle &h_encs)
{
    yarp::os::Stamp s;
    this->getEnvelope(s);
    double time = s.getTime();
    if(time !=0)
   {
        _prtImgIn->setHeadEncoders(time, h_encs);
    }
}
```

However the command **yarp read** able to display the envelope! @drdanz  @apaikan

**Comment by drdanz** [comment] 2016-05-31 13:47
I had this same problem some time ago, and I think I tested this with @apaikan, but with yarp read it disappeared, so I never went further with the testing.
At this point I believe that the issue might be in the type of port used, since `yarp read` uses a `yarp::os::PortReader`, and `camCalibWithPose` uses `yarp::os::BufferedPort`

**Comment by drdanz** [comment] 2016-06-20 10:13
See also #729

**Comment by drdanz** [comment] 2016-09-22 13:08
Duplicate of #909

**Comment by drdanz** [comment] 2016-09-26 13:42
Fixed in `devel`

**Closed by drdanz** 2016-09-26 13:42 UTC
Labels: Component: Carriers, Component: Library - YARP_OS, Resolution: Duplicate
