### ISSUE TITLE
"yarpdev --list" deadlock if clock is enabled

### ISSUE THREAD

**Issue by aerydna** [robotology/yarp#854] opened 2016-08-04 15:18 UTC
by starting yarpserver with the clock published (by gazebo in my trial) "yarpdev --list" freeze.

**Comment by aerydna** [comment] 2016-09-07 07:29
i've found that the issued is caused by a call to a 
1.  .toString() method 
2.  that calls a ConstString constructor 
3.  that calls a scan() method
4.  that calls yarp::os::Time::now() inside a Network::lock()
now, as @barbalberto suggest me, the clock is, basically, lazy initializated and in our case is been created at this call of Time::now(). but the initialization of the clock contains a Network::lock() that cause the deadlock().

the constraint here is that the clock can't be initializated (but, if already created, can be used) inside a Network::lock().

by moving the lines that contains the Time::now() call, in the YarpPluginSelector::scan() method, out of the Network::lock(), APPARENTLY all works fine but i doubt that this can be a definitive solution.

**Comment by traversaro** [comment] 2016-09-07 07:43
FYI, most of the history of development of NetworkClock support in YARP  can be read in this issue : https://github.com/robotology/gazebo-yarp-plugins/issues/57 .

**Comment by randaz81** [comment] 2016-09-13 11:53
This is pretty critical in many other applications and we need to fix it asap.
@barbalberto @drdanz What do you think?

**Comment by randaz81** [comment] 2016-09-16 14:59
@aerydna said that if a yarp::os::time::now() is called in the main() function, before using a yarp port, the problem seems not to appear.
However, this issue has be solved in yarp.

**Comment by drdanz** [comment] 2016-09-21 09:08
What do you think about creating the clock in `yarp::os::NetworkBase::initMinimum()` (that is called by `yarp::os::Network` constructor, called by any YARP module)?

**Comment by barbalberto** [comment] 2016-09-21 09:55
It'll probably work for this issue, but it feels more like a workaround to me... 
I think the problem is in the `Clock` and derived classes about how they create and handle the clock, and the solution should be found there.

Do anyone knows why the call `useNetworkClock` does not creates the clock but uses instead the lazy initilization?
The only reason I may think of, is that maybe the yarpserver itself will hangs if run with YARP_CLOCK. If this is the case, maybe can yarpserver ignore this setting since it does not need to run on simulated time?
In my tests, many times just creating the clock when required fixes this type of issues while delaying the creation of the clock leads to un-expected behaviours because we don't actually know when the change of clock will take effect.

**Comment by barbalberto** [comment] 2016-10-27 08:17
This has been fixed by commit 714bc50 on branch clockWIP (under testing)

**Comment by traversaro** [comment] 2017-08-10 08:09
Fixed in`devel` by https://github.com/robotology/yarp/pull/1277, I guess? cc @barbalberto

**Comment by barbalberto** [comment] 2017-08-10 08:13
yes, it is. `yarpdev --list` always uses system clock

**Closed by barbalberto** 2017-08-10 08:13 UTC
Labels: Severity: Major, Type: Bug
