### ISSUE TITLE
'yarp server --ros' on a windows machine leads to segfault

### ISSUE THREAD

**Issue by randaz81** [robotology/yarp#1156] opened 2017-03-30 17:11 UTC
segfault @ Contact RosNameSpace::rosify(const Contact& contact)  rosNameSpace.cpp
if _hostname variable out-of-bound error_ is fixed as shown in the snippet below, the segfault does not occurs but ros communication simply does not work

```
Contact RosNameSpace::rosify(const Contact& contact) {
    ConstString carrier = ((contact.getCarrier() == "rosrpc")  ? "rosrpc" : "http");
    ConstString hostname = contact.getHost();
    if (yarp::os::impl::NameConfig::isLocalName(hostname)) {
        char hn[NI_MAXHOST];
        yarp::os::gethostname(hn, sizeof(hn));
        hn[NI_MAXHOST-1] = '\0';
        hostname = hn;
    }
    return Contact(carrier, hostname, contact.getPort());
}
```

**Comment by aerydna** [comment] 2018-05-29 09:01
cannot reproduce the issue. we suspect it to be already fixed, if not, reopen.

**Comment by randaz81** [comment] 2018-05-29 09:04
fixed by what?

**Comment by randaz81** [comment] 2018-05-29 09:09
Since the issue is probably a missing communication layer in WSL, let's keep this open until Microsoft releases the next patch and let's try again.

**Comment by drdanz** [comment] 2018-05-29 09:35
@randaz81 can you explain how to reproduce this? We were not able to reproduce this with a MSVC build, but perhaps this happens on WSL only?

**Comment by traversaro** [comment] 2018-05-29 12:30
If there is some system call problem in WSL, you can check/report it in https://github.com/Microsoft/WSL/issues .

**Comment by drdanz** [comment] 2019-04-11 08:47
I can no longer reproduce this.
I suspect this was fixed when I changed `NI_MAXHOST` to `HOST_NAME_MAX`.
Anyway, If this is a WSL error, it does not belong here. Closing

**Closed by drdanz** 2019-04-11 08:47 UTC
Labels: Complexity: Low, Component: Library - YARP_OS, Component: ROS Integration, Issue Type: Bug, Platform: Windows
