### ISSUE TITLE
Fill in yarprobotinterface documentation

### ISSUE THREAD

**Issue by valegagge** [robotology/yarp#1485] opened 2017-12-05 15:07 UTC
The documentation of yarprobotinterface is a white page.
see [http://www.yarp.it/yarprobotinterface.html](url)

**Comment by gsaponaro** [comment] 2017-12-05 15:31
https://github.com/robotology/yarp/issues/870

**Comment by drdanz** [comment] 2017-12-07 10:28
Duplicate of #870

**Closed by drdanz** 2017-12-07 10:28 UTC
Labels: Component: Documentation, Resolution: Duplicate
