### ISSUE TITLE
Non-deterministic memory leak in FrameTransformClientTest

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#953] opened 2016-11-10 08:12 UTC
See #880

**Comment by claudiofantacci** [comment] 2016-11-10 08:20
I suggest to set this to a (somewhat) "high priority" as it affects all the CI tests, and restarting them hoping for a lucky run is somewhat odd.

**Comment by drdanz** [comment] 2016-11-10 12:52
Assigning @aerydna since he was already working on this.

**Comment by aerydna** [comment] 2016-11-17 16:22
ok the test is fixed with the pr #960  but the issue is not. the problem was caused by the usage of tcp protocol for the streaming comunication between transformServer and Client. Details on the fresh related issue  #963

**Closed** 2016-11-17 17:41 UTC
Labels: Component: Library - YARP_dev, Component: Tests, Priority: High, Target: YARP v2.3.68, Type: Bug
