### ISSUE TITLE
Portables generated from ROS .msg files do not provide fully-ROS-compatible md5sum

### ISSUE THREAD

**Issue by elen4** [robotology/yarp#325] opened 2014-12-01 16:09 UTC
When advertising a ROS topic from Yarp, apparently `*` is used as md5sum for the message. While this allows ROS nodes to subscribe to such topic without problems, when replaying a bag file recorded from that topic the following *FATAL* error occurs:
>  Advertising with * as the md5sum is not allowed

**Comment by paulfitz** [comment] 2015-01-06 18:24
@elen4 pointed out that `d41d8cd98f00b204e9800998ecf8427e` is the checksum for the empty string, and that the problem is likely to be yarp's failure to include full plaintext nested type definitions in the tcpros header.

**Comment by paulfitz** [comment] 2015-01-07 20:51
Committed improvements to md5sum generation, and validated it against all ros messages (in a random ros install). Also added a first pass at a message_definition field, but this part is not yet validated.

**Comment by paulfitz** [comment] 2015-01-08 17:37
rosbag tests added in 7f545c904b7628ca2015f87f7c98981831bc7b5d, more to come.

**Comment by paulfitz** [comment] 2015-01-13 19:53
Closing this, seems to work well now. Tests caught one bug in serialization of lists of user-defined structures, now fixed in 621af29d62cc97d740b9426c0be1134ecc0dca93

**Closed by paulfitz** 2015-01-13 19:53 UTC
Labels: Component: yarpros, Severity: Minor, Type: Bug
