### ISSUE TITLE
ITorqueControl2

### ISSUE THREAD

**Issue by francesco-romano** [robotology/yarp#176] opened 2014-05-07 18:46 UTC
I think we need an implementation of a version of `ITorqueControl` which can communicate using streaming ports and which implements the `setRefTorques` version with joint list (the equivalent of `IPositionControl2` and `IVelocityControl2`)

**Comment by randaz81** [comment] 2015-06-19 09:17
@francesco-romano @traversaro
Some time has passed, can you report on the current status of this issue?
Have all the modifications been merged into master?

**Comment by traversaro** [comment] 2015-06-19 09:30
At the moment, no ITorqueControl2 interface has been implemented. 

By ITorqueControl2 I mean an interface that supports setting multiple reference torques in a subset of the joints of the controlboard, with methods like:
`setRefTorque(const int n_joint, const int *joints, const double *refs)`

This is inconvenient especially for the arms: we will always control in torque mode just a subset of the joints (for sure we will never control the hand in torque mode, and even in that case the hand will not be managed by the whole-body controller) and at the moment we have to send a streaming message for each joint. Furthermore we have to take care to use the `writeStrict` option to avoid that the reference torque on a joint gets overwritten by a reference torque on another joint.

**Comment by randaz81** [comment] 2015-06-19 10:02
:+1: It seems a one-day task. Assigned to @randaz81 or @barbalberto depending on the preference/time availability.

**Comment by traversaro** [comment] 2015-06-19 10:11
:+1: :+1:

**Comment by pattacini** [comment] 2015-06-21 12:13
A problem has been spotted very recently regarding the `writeStrict` option: see https://github.com/robotology/icub-main/issues/129#issuecomment-113787053.

**Comment by barbalberto** [comment] 2015-06-26 12:30
Upon request from @randaz81 I implemented the group version of setRefTorque.
In order to not create a new interface for just a single command, the new function was implemented not as a pure virtual call but with a default {return false} implementation, which allows to keep back compatibility.

Is it ok for everybody? The update is in the 'setRefTorque_group' branch for both yarp and iCub. No source version number has been changed, nor protocol version numbber. Shall I upgrade it?

The function has been implemented in eth, can & icubSim motion controllers (as well as in remoteControlBoard and the wrapper of course).
Gazebo, coman, walkman and robotran are not updated yet.

**Comment by barbalberto** [comment] 2015-06-26 12:31
Ah, also simpleClient has been updated to include this command

**Comment by traversaro** [comment] 2015-06-26 12:54
:+1: :+1: 

I would for sure update the yarp version number, because if we want for example to implement this in `gazebo-yarp-plugins` we have to depend on a version of yarp that supports it. 

Not sure about the protocol number.. which incompatibility rules exist for protocol number? Both `client` and `server` must share the exact same protocol number?

What happens if a client and a server are updated to use setRefTorques (group version) but the wrapped devices does not support it?

**Comment by barbalberto** [comment] 2015-06-26 13:25
Yes, both client and server ust agree on the protocol number.

Without updating the protocol number:
If the client is updated and the wrapper (robot/simulator) is not, the new message will be discarded, maybe some noisy print could show up, not sure about it.

Updating the protocol number:
If the client is updated and the wrapper (robot/simulator) is not, initial protocol check fails and remoteControlBoard will close, forcing the update.

**Comment by traversaro** [comment] 2015-06-26 23:20
I am a bit afraid of the use case of the updated client that is sending torques to a not updated robot and then (misteriously) nothing happens.. On the other hand breaking the controlboard compatibility with the released version ( just released, by che way) is not so noce.

**Comment by barbalberto** [comment] 2015-07-07 09:23
I think a new message actually IS a change in the protocol so I'm for updating it as well. If a user work with the robot is his/her duty to be updated and it is better than have a code that runs with unexpected behaviour. 

@lornat75 what do you think about implementing the function with a **default implementation instead of pure virtual** and about the protocol number?

**Comment by pattacini** [comment] 2015-07-07 11:31
Adopting "default implementation" vs. "pure virtual" could have solved many problems in the past, however now it is also a matter of neatness, since such an adoption will break the symmetry with other interfaces...

**Comment by lornat75** [comment] 2015-07-07 13:00
+1 for updating the protocol number
+1 for default virtual functions

**Comment by traversaro** [comment] 2015-07-07 13:03
Notice that updating the protocol number will mean that VVV users will not be able to use the binary version of yarp and icub to control the real robots.

**Comment by traversaro** [comment] 2015-07-07 13:06
Unless we do a new yarp release before VVV.

**Comment by barbalberto** [comment] 2015-07-07 13:06
Or set the robots to a compatible git commit for that week ;)

**Comment by traversaro** [comment] 2015-07-07 13:09
In that case, people with yarp master (i.e. that installed yarp from sources) will not be able to use the real robots... unless they point to a compatible git commit, but I thinks everything could escalate quick to a big mess.

**Comment by lornat75** [comment] 2015-07-07 13:15
We can ask vvv users to use yarp + icub from master -- it is not a big deal.

**Comment by traversaro** [comment] 2015-07-07 13:26
Perfect.

**Comment by barbalberto** [comment] 2015-07-07 13:35
Ok, so I'll update the numbers and merge tomorrow morning

**Comment by traversaro** [comment] 2015-09-02 10:27
Fixed by https://github.com/robotology/yarp/pull/527 .

**Closed by traversaro** 2015-09-02 10:27 UTC
Labels: Component: YARP_dev
