### ISSUE TITLE
Link to yarp installation instructions is broken

### ISSUE THREAD

**Issue by gabrielenava** [robotology/yarp#1228] opened 2017-05-23 10:15 UTC
Following the instructions in [this page](http://wiki.icub.org/wiki/Linux:Installation_from_sources), I was trying to open the link with the instructions that explain how to install yarp:

 http://wiki.icub.org/yarp/specs/dox/user/html/install_yarp_linux.html

but apparently the link is broken. Actually, it seems also this page does not exist anymore:

www.yarp.it/install.html

but since few weeks ago, I was able to reach it from my pc.

**Comment by traversaro** [comment] 2017-05-23 10:18
Duplicate of https://github.com/robotology/yarp/issues/1218 , @mbrunettini was working on that , what is the status? 
In the meanwhile you can access it at www.yarp.it/master/install.html

**Comment by mbrunettini** [comment] 2017-05-23 10:59
Link updated

**Closed by mbrunettini** 2017-05-23 10:59 UTC
